# https://taskfile.dev

version: '3'


tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  package-koel:
    #language=sh
    cmds:
      - >
        helm package charts/koel 
        --destination repo
        --dependency-update
    aliases:
      - pk

  repo-update-index:
    #language=sh
    cmds:
      - >
        helm repo index repo
    aliases:
      - rui