apiVersion: v1
kind: Secret
metadata:
  name: {{ include "koel.fullname" . }}-mysql-secret
  labels:
    {{- include "koel.labels" . | nindent 4 }}
data:
  username: {{ .Values.mysql.auth.username | b64enc }}
  password: {{ .Values.mysql.auth.password | b64enc }}
