# koel/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "koel.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ template "koel.fullname" . }}
  selector:
    matchLabels:
      {{- include "koel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "koel.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: {{ .Values.mysql.fullnameOverride }}
            - name: DB_DATABASE
              value: {{ .Values.mysql.auth.database }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "koel.fullname" . }}-mysql-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "koel.fullname" . }}-mysql-secret
                  key: password
          volumeMounts:
            - name: music-pvc
              mountPath: /music
            - name: covers-pvc
              mountPath: /var/www/html/public/img/covers
            - name: search-index-pvc
              mountPath: /var/www/html/storage/search-indexes
  volumeClaimTemplates:
    - metadata:
        name: music-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.storage.musicSize }}
    - metadata:
        name: covers-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.storage.coversSize }}
    - metadata:
        name: search-index-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.storage.searchIndexSize }}